Test shared JS tests on all supported Node versions
sass/sass-spec pull request #1713
Opened 2021-09-15 22:39 UTC by nex3

2021-09-15 23:02 UTC, stof requested changes

2021-09-15 23:02 UTC, stof commented on .github/workflows/ci.yml
> +        with: {node-version: "${{ env.node_version }}"}
should be `matrix.node_version`

2021-09-15 23:26 UTC, Awjin approved these changes

2021-09-16 00:19 UTC, Awjin commented
The refactors LGTM.

2021-09-16 01:54 UTC, merged