Test invalid contents for importer results
sass/sass-spec pull request #1834
Opened 2022-11-01 01:30 UTC by Goodwine

Test invalid arguments for importer results.
    
- Tests contents not being string values
- Tests SassException argument errors have better output
- Adds sandbox directory to .gitignore

See https://github.com/sass/dart-sass/pull/1816

[skip dart-sass]

2022-11-01 23:24 UTC, nex3 requested changes

2022-11-01 23:24 UTC, nex3 commented on js-api-spec/importer.test.ts
> +      dir.write({'dir/_other.scss': '// non empty file'});
It's probably overkill to create a whole sandbox to read from here when you could just construct and return a `Buffer` in memory.

2022-11-03 23:48 UTC, nex3 approved these changes

2022-11-03 23:50 UTC, merged

2022-11-04 05:23 UTC, ntkme commented
@Goodwine This is failing on dart-sass-embedded and cause the test to completely stuck:
```
FAIL js-api-spec/legacy/importer.test.ts (13.351 s)
  ● when importer returns non-string contents › throws an error in sync mode
    expected exception.toString() to contain "Invalid argument (contents): must be a string but was: Buffer: Instance of 'NativeUint8List'", was "Error: expected "{".
      ╷
    1 │ not a string
      │             ^
      ╵
      other 1:13  @import
      - 1:9       root stylesheet"
      875 |         },
      876 |       });
    > 877 |     }).toThrowLegacyException({
          |        ^
      878 |       line: 1,
      879 |       includes:
      880 |         'Invalid argument (contents): must be a string but was: Buffer: ' +
      at Object.<anonymous> (js-api-spec/legacy/importer.test.ts:877:8)
  ● when importer returns non-string contents › throws an error in async mode
    expected exception.toString() to contain "Invalid argument (contents): must be a string but was: Buffer: Instance of 'NativeUint8List'", was "Error: expected "{".
      ╷
    1 │ not a string
      │             ^
      ╵
      other 1:13  @import
      - 1:9       root stylesheet"
      899 |         expect(() => {
      900 |           throw err;
    > 901 |         }).toThrowLegacyException({
          |            ^
      902 |           line: 1,
      903 |           includes:
      904 |             'Invalid argument (contents): must be a string but was: ' +
      at js-api-spec/legacy/importer.test.ts:901:12
      at ../embedded-host-node/lib/src/legacy/index.ts:56:[16](https://github.com/sass/sass-spec/actions/runs/3391409147/jobs/5636555116#step:9:17)
  ● when importer returns non-string contents › throws an error in async mode
    thrown: "Exceeded timeout of 5000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."
      883 |   });
      884 |
    > 885 |   it('throws an error in async mode', done => {
          |   ^
      886 |     sass.render(
      887 |       {
      888 |         data: '@import "other";',
      at js-api-spec/legacy/importer.test.ts:885:3
      at Object.<anonymous> (js-api-spec/legacy/importer.test.ts:863:1) 
```

2022-11-04 05:46 UTC, ntkme commented
I tested locally:

- Dart Sass Embedded would throw an error, but the error message is different. The error message can be different across implementations, so that we should probably remove them from the current test.
- When sourceMapUrl is a non-empty string but not absolute, Dart Sass Embedded does throw an error but `span` is `null`, this should get fixed.

2022-11-05 18:53 UTC, Goodwine commented
Yeah, I guess it is not necessary to include all data, I'll send a PR unless there is one already

2022-11-05 19:03 UTC, Goodwine commented
Hm.. although it looks like the only reason it's failing is because the value was actually returned as a string but just not valid sass 🤔, maybe it's better to not-return a buffer and return other invalid data?