Add tests for Color is Legacy
sass/sass-spec pull request #1842
Opened 2022-11-23 20:35 UTC by SondraE

2022-11-28 22:56 UTC, nex3 commented
We should target these color space PRs to separate branch (`color-4` would match the branch name in the Dart Sass repo). If we land them on `main`, it'll break our CI since the actual implementation of the behavior in question isn't finished yet.

2022-11-30 14:15 UTC, dvdherron commented
> We should target these color space PRs to separate branch (`color-4` would match the branch name in the Dart Sass repo). If we land them on `main`, it'll break our CI since the actual implementation of the behavior in question isn't finished yet.

@nex3 I don't think we have the right access here to make a new branch. If you create the branch I can re-target these color PRs.

2022-12-01 01:29 UTC, nex3 commented
@dvdherron Done :smiley: 

@SondraE You should be able to fix the lint errors by running `npm run lint-spec -- --fix`. I'm not sure why the Dart Sass tests are running, but they may go away if you run the tests again now that you have `[skip dart-sass]`.

2022-12-01 01:31 UTC, nex3 requested changes

2022-12-01 01:31 UTC, nex3 commented on spec/core_functions/color/is_legacy.hrx
> +<===> error/too_few_args/input.scss
These may not need explicit outputs, but they do need inputs to test against :sweat_smile:

2022-12-13 01:22 UTC, nex3 requested changes

2022-12-13 01:22 UTC, nex3 commented on spec/core_functions/color/is_legacy.hrx
> +a {b: color.is-legacy(rgb(0 255))}
This is passing too few args to `rgb()`, but it should be passing too few args to `is-legacy()`

2022-12-13 01:22 UTC, nex3 commented on spec/core_functions/color/is_legacy.hrx
> +a {b: color.is-legacy($color: midnightblue)}
It looks like this is testing both a named argument _and_ a named color—we should have separate tests for each of these cases (see https://github.com/sass/sass-spec/blob/main/STYLE_GUIDE.md#do-test-only-one-thing-per-spec)

2022-12-13 01:38 UTC, nex3 commented
Removing `[skip dart-sass]` since I don't think this will require any code changes in Dart Sass

2022-12-13 02:16 UTC, nex3 commented
JS API test failures are unrelated, I'm working on fixing them in https://github.com/sass/sass-spec/pull/1853

2022-12-14 02:23 UTC, nex3 approved these changes

2022-12-14 02:23 UTC, merged