Add tests for the indented syntax
sass/sass-spec pull request #2034
Opened 2024-10-24 13:12 UTC by jamesnw

This adds minimal coverage to the indented syntax, with focus on the areas that may change with upcoming improvements, specifically line breaks and white space parsing.

2024-10-24 22:20 UTC, nex3 reviewed
Please take a look at the [style guide](https://github.com/sass/sass-spec/blob/main/STYLE_GUIDE.md) for HRX tests, in particular the sections on irrelevant placeholders and testing one thing per spec. I think a fair number of these are more complex than they need to be in an attempt to test realistic CSS, but here terse is better than realistic.

I recommend adding some error tests as well to cover cases that are invalid, especially ones that may differ in the new system.

2024-10-28 21:50 UTC, jamesnw commented
@nex3 Do you have a preference between adding tests to a new `indented-syntax` folder vs. adding .sass variations of tests to files like [sass-spec/spec/directives/for.hrx](https://github.com/sass/sass-spec/blob/main/spec/directives/for.hrx)?

2024-10-30 21:12 UTC, jamesnw commented
@nex3 I've made changes per the style guide, and merged in with the existing file structure. I also found https://github.com/sass/sass-spec/tree/main/spec/non_conformant/sass and wasn't sure if it would make sense to have a `syntax/sass` folder to hold some of these, and maybe some of the non_conformant ones?

2024-10-30 23:13 UTC, nex3 requested changes
You can generally ignore the non-conformant tests, although if you notice that you're writing tests that cover all the same cases go ahead and delete the redundant non-conformant tests.

2024-10-30 23:13 UTC, nex3 commented on spec/css/custom_properties/trailing_whitespace.hrx
> +<===> sass/input.sass
If we're adding new tests, we should make them style-guide-conformant even if they're largely copies of old tests. Bonus points to make the old tests conformant as well.

2024-10-30 23:13 UTC, nex3 commented on spec/arguments/invocation.hrx
> +<===> function/error/multi-line-arguments/declaration/input.sass
Anything that's specifically testing the indented syntax should probably have `/sass/` somewhere in the path.

2024-10-31 22:33 UTC, nex3 approved these changes

2024-10-31 22:33 UTC, nex3 commented on spec/directives/if/indented.hrx
Rather than adding `sass/` at the beginning of these HRX entries, rename the file to `sass` to match the other directories. (The logical directory name for each test is the physical name followed by the HRX name, so `indented/sass` is redundant.)

2024-11-04 23:34 UTC, nex3 commented on spec/css/custom_properties/trailing_whitespace.hrx
> +  --b: c;
There's a design conflict here between "trailing whitespace in custom property values is observable in CSS" and "end-of-line trailing whitespaces is invisible and generally shouldn't matter", complicated further by the fact that custom property trailing whitespace *nearly* never matters in practice. I think given that we're planning to allow `--b: c ;` in the indented syntax eventually anyway, preserving the existing behavior is probably the right way forward.

2024-11-04 23:34 UTC, merged