[Indented syntax improvements] Specs
sass/sass-spec pull request #2041
Opened 2024-12-16 18:51 UTC by jamesnw

Blocked until [proposal](https://github.com/sass/sass/blob/main/proposal/indented-syntax-improvements.md) is accepted.

[ ] dart-sass (coming soon)

[skip dart-sass]
[skip sass-embedded]

2025-01-23 01:51 UTC, nex3 requested changes
Other expressions that should probably have whitespace tests include parentheses and function calls.

2025-01-23 01:51 UTC, nex3 commented on spec/directives/function/whitespace.hrx
> +<===> nested_at_rule/debug/scss/input.scss
I'm not sure there's a point in testing multiple different nested at rules. That just seems like combinatorially many tests for little value.

2025-01-23 01:51 UTC, nex3 commented on spec/directives/in_declarations.hrx
I'm not sure why these need their own distinct whitespace tests

2025-01-23 01:51 UTC, nex3 commented on spec/directives/return.hrx
Doesn't this need whitespace tests?

2025-01-23 01:51 UTC, nex3 commented on spec/directives/while.hrx
This directory name doesn't include "whitespace" anywhere.

2025-01-23 01:51 UTC, nex3 commented on spec/expressions/comments.hrx
> +<===> loud/sass/inline-closed/input.sass
Why use a hyphen here instead of a directory separator?

2025-01-23 01:51 UTC, nex3 commented on spec/expressions/comments.hrx
> +<===> whitespace-comment/sass/inline/input.sass
I think "comment" here is redundant. If you're trying to emphasize that the comment is being parsed as a whitespace, I'd call this `as_whitespace`.

2025-01-23 01:51 UTC, nex3 commented on spec/expressions/variable.hrx
A semicolon doesn't make sense for a variable *expression*.

2025-01-23 01:51 UTC, nex3 commented on spec/operators/boolean.hrx
I'm concerned that these tests have no output verification, which means they could compile for unexpected reasons with unexpected semantics and still pass.

2025-01-23 01:51 UTC, nex3 commented on spec/operators/boolean.hrx
> +not c
Unary operators shouldn't be tested in the same way as binary operators, since they aren't parsed in the same way.

2025-01-23 01:51 UTC, nex3 commented on spec/operators/boolean.hrx
I don't think you need to test whitespace separately for each separate operator type. All binary operators are parsed essentially the same.

2025-01-23 01:51 UTC, nex3 commented on spec/parser/interpolation.hrx
I don't think you need to test this separately for every place an interpolation can appear.

2025-01-23 01:51 UTC, nex3 commented on spec/parser/selector.hrx
> +<===> multiline-no-comma/input.sass
This should probably go under `whitespace/`.

2025-01-23 01:51 UTC, nex3 commented on spec/parser/selector.hrx
What about cases like `a\n, b` and `a +\nb`?

2025-01-23 01:51 UTC, nex3 commented on spec/parser/semicolon.hrx
Aren't these redundant with the tests you have in individual statement directories?

2025-01-28 18:34 UTC, jamesnw reviewed
@nex3 I think I resolved all the issues.

> Other expressions that should probably have whitespace tests include parentheses and function calls.

For parentheses, I do have tests in spec/values/maps/sass.hrx and spec/values/lists/sass.hrx, and also expanded tests in functions and parentheses in 271999543df62b56589f07437689a374e32b0651. 

This also caught a bug in parsing `@function a($b: c\nd)`. I fixed this and changed `expressionUntilComma` to always consume whitespace (because it is currently only called in places that can consume whitespace) here-
https://github.com/sass/dart-sass/pull/2467/commits/e1df2ad69f4f4c93cecc1bbe2f2a8e6c12721b0f

2025-01-30 00:10 UTC, nex3 reviewed
Pretty close!

2025-01-30 00:10 UTC, nex3 commented on spec/core_functions/global/newlines.hrx
The `core_functions` directory is for testing the semantics of functions. Function call syntax doesn't differ between built-in, user-defined, and plain-CSS functions (except that the latter allows interpolation and not namepsaces) so syntactic tests for functions should go in a single, syntax-oriented location.

2025-01-30 00:10 UTC, nex3 commented on spec/css/media/whitespace.hrx
> +<===> error/logic_sequence/before_operator/sass/input.sass
The error directory should go at the end of the HRX file.

2025-01-30 00:10 UTC, nex3 commented on spec/directives/extend/whitespace.hrx
> +<===> error/after_arg/sass/input.sass
Also test `@extend a\nb`.

2025-01-30 00:10 UTC, nex3 commented on spec/directives/mixin/sass.hrx
> +  @content;
Why a semicolon?

2025-01-30 17:25 UTC, jamesnw commented on spec/core_functions/global/newlines.hrx
Moved to spec/expressions/functions in 5a5ff4562c6088ef998101b60150acca9bc1b5e2, and also switched to using `list.append` so I'm not using a deprecated function.

2025-01-30 17:25 UTC, jamesnw commented on spec/directives/mixin/sass.hrx
> +  @content;
This was porting over a nonconformant test, originally in [spec/non_conformant/sass/semicolon/content.hrx](https://github.com/sass/sass-spec/blob/main/spec/non_conformant/sass/semicolon/content.hrx#L5). Should it be removed?

2025-01-30 17:25 UTC, jamesnw commented on spec/css/media/whitespace.hrx
> +<===> error/logic_sequence/before_operator/sass/input.sass
Moved in cd4eced4e5e1125de252490046e5eff6d498da20

2025-01-30 17:26 UTC, jamesnw commented on spec/directives/extend/whitespace.hrx
> +<===> error/after_arg/sass/input.sass
Tested in cd4eced4e5e1125de252490046e5eff6d498da20

2025-02-01 00:43 UTC, nex3 requested changes

2025-02-01 00:43 UTC, nex3 commented on spec/directives/extend/whitespace.hrx
This still doesn't have a test for `@extend a\nb`

2025-02-01 02:25 UTC, jamesnw commented on spec/directives/extend/whitespace.hrx
🤦 Sorry. Added in 3af370809457f5eb8927fd78bfc69af2abd942bb.

2025-02-03 23:48 UTC, nex3 approved these changes

2025-02-05 23:33 UTC, merged